                                            Self-Driving Car Research Project

                                                   Data Preprocessing

In [1]:
from __future__ import print_function
from imutils.object_detection import non_max_suppression
from imutils import paths
import numpy as np
import os
import imutils
import cv2

In [5]:
dirs = os.listdir('Images')
for i in range(0,len(dirs)):
    dirs[i] = os.path.join('Images', dirs[i])
paths = []
for dir in dirs:
    files = os.listdir(dir)
    for file in files:
        paths.append(os.path.join(dir,file))

In [6]:

# initialize the HOG descriptor/person detector
hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())

In [7]:
# loop over the image paths
for imagePath in paths:
    # load the image and resize it to (1) reduce detection time
    # and (2) improve detection accuracy
    print(imagePath)
    image = cv2.imread(imagePath)
    print(image)
    image = imutils.resize(image, width=min(400, image.shape[1]))
    orig = image.copy()
 
    # detect people in the image
    (rects, weights) = hog.detectMultiScale(image, winStride=(4, 4),
        padding=(8, 8), scale=1.05)
 
    # draw the original bounding boxes
    for (x, y, w, h) in rects:
        cv2.rectangle(orig, (x, y), (x + w, y + h), (0, 0, 255), 2)
 
    # apply non-maxima suppression to the bounding boxes using a
    # fairly large overlap threshold to try to maintain overlapping
    # boxes that are still people
    rects = np.array([[x, y, x + w, y + h] for (x, y, w, h) in rects])
    pick = non_max_suppression(rects, probs=None, overlapThresh=0.65)
 
    # draw the final bounding boxes
    for (xA, yA, xB, yB) in pick:
        cv2.rectangle(image, (xA, yA), (xB, yB), (0, 255, 0), 2)
 
    # show some information on the number of bounding boxes
    filename = imagePath[imagePath.rfind("/") + 1:]
    print("[INFO] {}: {} original boxes, {} after suppression".format(
        filename, len(rects), len(pick)))
 
    # show the output images
    cv2.imshow("Before NMS", orig)
    cv2.imshow("After NMS", image)
    # Press any key to go on to the next image
    cv2.waitKey(0)

Images/10/2017_1226_151624_000138.png
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 246 246]
  [255 248 245]
  [255 248 245]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 246 246]
  [255 248 245]
  [255 248 245]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 246 246]
  [255 248 245]
  [255 248 245]]

 ...

 [[  0 129 174]
  [  0 129 174]
  [  0 129 174]
  ...
  [ 86  63  62]
  [ 86  63  62]
  [ 88  65  64]]

 [[  0 129 174]
  [  0 129 174]
  [  0 129 174]
  ...
  [ 86  63  62]
  [ 86  63  62]
  [ 89  66  65]]

 [[  0 129 174]
  [  0 129 174]
  [  0 129 174]
  ...
  [ 86  63  62]
  [ 91  68  67]
  [ 95  72  71]]]
[INFO] 2017_1226_151624_000138.png: 0 original boxes, 0 after suppression
Images/10/2017_1226_141643_003034.png
[[[160 134 102]
  [147 121  89]
  [151 125  93]
  ...
  [255 255 243]
  [255 255 244]
  [255 255 245]]

 [[162 136 104]
  [150 124  92]
  [155 129  97]
  ...
  [255 255 243]
  [255 255 244]
  [255 255 245]]

 [[169 143 1

[INFO] 2017_1226_132817_002422.png: 0 original boxes, 0 after suppression
Images/10/2017_1218_163751_001877.png
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 245 233]
  [255 245 233]
  [255 245 233]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 245 233]
  [255 245 233]
  [255 245 233]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 245 233]
  [255 245 233]
  [255 245 233]]

 ...

 [[ 16 109 135]
  [ 14 107 133]
  [ 19 112 138]
  ...
  [101  91  86]
  [ 81  71  66]
  [ 78  68  63]]

 [[  7 100 126]
  [ 21 114 140]
  [ 23 116 142]
  ...
  [ 92  82  77]
  [ 86  76  71]
  [ 81  71  66]]

 [[  7 100 126]
  [ 14 107 133]
  [  9 102 128]
  ...
  [ 83  73  68]
  [ 83  73  68]
  [106  96  91]]]
[INFO] 2017_1218_163751_001877.png: 1 original boxes, 1 after suppression
Images/10/2017_1218_154110_003632.png
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 236 201]
  [255 236 201]
  [255 236 201]]

 [[255 255 255]
  [255 255 255]
  [255 255

Images/00/2017_1218_154708_002762.png
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[  0 151 194]
  [  0 158 201]
  [  0 158 201]
  ...
  [ 83  71  57]
  [ 76  64  50]
  [ 69  57  43]]

 [[  0 153 196]
  [  0 154 197]
  [  0 154 197]
  ...
  [ 90  77  66]
  [ 93  80  69]
  [ 69  56  45]]

 [[  0 157 200]
  [  0 152 195]
  [  0 152 195]
  ...
  [ 86  73  62]
  [ 89  76  65]
  [ 52  39  28]]]
[INFO] 2017_1218_154708_002762.png: 0 original boxes, 0 after suppression
Images/00/2017_1226_161604_001038.png
[[[255 253 235]
  [255 253 235]
  [255 253 235]
  ...
  [255 234 211]
  [255 234 211]
  [255 234 211]]

 [[255 253 235]
  [255 253 235]
  [255 253 235]
  ...
  [255 234 211]
  [255 234 211]
  [255 234 211]]

 [[255 253 2

[INFO] 2017_1226_161006_002559.png: 0 original boxes, 0 after suppression
Images/00/2017_1226_153418_001431.png
[[[251 232 206]
  [251 232 206]
  [251 232 206]
  ...
  [255 221 193]
  [254 218 190]
  [253 217 189]]

 [[251 232 206]
  [251 232 206]
  [251 232 206]
  ...
  [255 221 193]
  [255 219 191]
  [255 219 191]]

 [[251 232 206]
  [251 232 206]
  [251 232 206]
  ...
  [255 221 193]
  [255 222 194]
  [255 224 196]]

 ...

 [[  0 236 255]
  [  0 236 255]
  [  0 236 255]
  ...
  [ 43  41  46]
  [ 73  71  76]
  [ 82  80  85]]

 [[  0 236 255]
  [  0 236 255]
  [  0 236 255]
  ...
  [ 33  31  36]
  [ 66  64  69]
  [ 90  88  93]]

 [[  0 236 255]
  [  0 236 255]
  [  0 236 255]
  ...
  [ 54  52  57]
  [ 61  59  64]
  [ 67  65  70]]]
[INFO] 2017_1226_153418_001431.png: 0 original boxes, 0 after suppression
Images/00/2017_1226_151026_002804.png
[[[242 202 164]
  [242 202 164]
  [242 202 164]
  ...
  [247 203 156]
  [247 203 156]
  [247 203 156]]

 [[242 202 164]
  [242 202 164]
  [242 202

Images/01/2017_1226_161305_003403.png
[[[255 239 220]
  [255 239 220]
  [255 239 220]
  ...
  [236 200 197]
  [247 215 209]
  [223 191 185]]

 [[255 239 220]
  [255 239 220]
  [255 239 220]
  ...
  [255 234 231]
  [217 185 179]
  [126  94  88]]

 [[255 239 220]
  [255 239 220]
  [255 239 220]
  ...
  [205 169 166]
  [116  84  78]
  [ 68  36  30]]

 ...

 [[  0 193 253]
  [  0 193 253]
  [  0 193 253]
  ...
  [ 96  86  93]
  [ 92  82  89]
  [ 88  78  85]]

 [[  0 193 253]
  [  0 193 253]
  [  0 193 253]
  ...
  [ 92  82  89]
  [ 78  68  75]
  [ 68  58  65]]

 [[  0 193 253]
  [  0 193 253]
  [  0 193 253]
  ...
  [ 85  75  82]
  [ 85  75  82]
  [ 57  47  54]]]
[INFO] 2017_1226_161305_003403.png: 1 original boxes, 1 after suppression
Images/01/2017_1225_161305_000540.png
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [123 115 115]
  [134 126 126]
  [158 150 150]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [145 137 137]
  [151 143 143]
  [157 149 149]]

 [[255 255 2

[INFO] 2017_1226_155810_000609.png: 1 original boxes, 1 after suppression
Images/01/2017_1226_152820_000256.png
[[[232 199 161]
  [232 199 161]
  [232 199 161]
  ...
  [198 157 114]
  [206 165 122]
  [237 196 153]]

 [[232 199 161]
  [232 199 161]
  [232 199 161]
  ...
  [198 157 114]
  [213 172 129]
  [243 202 159]]

 [[232 199 161]
  [232 199 161]
  [232 199 161]
  ...
  [195 154 111]
  [228 187 144]
  [255 214 171]]

 ...

 [[  0 206 246]
  [  0 206 246]
  [  0 206 246]
  ...
  [ 57  58  45]
  [ 35  36  23]
  [ 57  58  45]]

 [[  0 206 246]
  [  0 206 246]
  [  0 206 246]
  ...
  [ 74  75  62]
  [ 69  70  57]
  [ 63  64  51]]

 [[  0 206 246]
  [  0 206 246]
  [  0 206 246]
  ...
  [ 78  79  66]
  [ 80  81  68]
  [ 78  79  66]]]
[INFO] 2017_1226_152820_000256.png: 0 original boxes, 0 after suppression
Images/01/2017_1226_161006_004438.png
[[[249 235 213]
  [249 235 213]
  [249 235 213]
  ...
  [255 252 244]
  [255 234 225]
  [255 224 215]]

 [[249 235 213]
  [249 235 213]
  [249 235